name: test_today
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  responsive_framework: ^0.2.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  shimmer: ^2.0.0
  logger: ^1.1.0
  loading_animation_widget: ^1.2.0+3
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0
  carousel_slider: ^4.1.1
  go_router: ^5.2.0
  file_picker: ^5.2.3
  awesome_dialog: ^3.0.2
  url_launcher: ^6.1.7
  dio: ^4.0.6
  flutter_local_notifications: ^12.0.4
  intl: ^0.18.0
  map_launcher: ^2.5.0+1
  geolocator: ^9.0.0
  flutter_geocoder: ^0.2.2-nullsafety
  geocoding: ^2.0.5
  latlng:




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
