name: test_pro
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  web_socket_channel:
  provider: ^6.0.5
  flutter_bloc: ^8.1.2
  flutter_riverpod: ^2.2.0
  rxdart: ^0.27.7
  flutter_svg:
  convex_bottom_bar: ^3.2.0
  flutter_responsive_scale: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/menu.svg
    - assets/welcome.png
    - assets/banner.jpeg
    - assets/banner2.jpeg
    - assets/van.png
    - assets/vansvg.svg


